-- 1) productos.id: server-generated ids -----------------------------------------
-- The client used to mint ids with a counter that restarted at 1000 on every page
-- load, so a new product could overwrite an existing one through upsert. BY DEFAULT
-- (not ALWAYS) keeps explicit ids working for updates and imports.
alter table public.productos alter column id add generated by default as identity;

select setval(
  pg_get_serial_sequence('public.productos', 'id'),
  coalesce((select max(id) from public.productos), 0) + 1,
  false
);

-- 2) registrar_venta: one transaction per sale ------------------------------------
-- Replaces the client-side createSale -> insertSaleItems -> updateProductStock chain,
-- which left half-written sales when a later step failed and computed the new stock
-- from a stale client copy (lost updates between devices). Any error here rolls the
-- whole call back. Overselling is still allowed on purpose (no stock >= 0 check).
create function public.registrar_venta(
  p_negocio_id bigint,
  p_jornada_id text,
  p_pago       text,
  p_total      numeric,
  p_items      jsonb
) returns public.ventas
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_venta public.ventas;
  v_item  record;
begin
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'registrar_venta: the sale needs at least one item';
  end if;

  insert into public.ventas (negocio_id, jornada_id, fecha, total, pago)
  values (p_negocio_id, p_jornada_id, now(), p_total, p_pago)
  returning * into v_venta;

  for v_item in
    select * from jsonb_to_recordset(p_items) as x(
      producto_id bigint, nombre text, cantidad numeric,
      unidad text, precio_unitario numeric, subtotal numeric)
  loop
    insert into public.venta_items
      (venta_id, producto_id, nombre, cantidad, unidad, precio_unitario, subtotal)
    values
      (v_venta.id, v_item.producto_id, v_item.nombre, v_item.cantidad,
       v_item.unidad, v_item.precio_unitario, v_item.subtotal);

    update public.productos
       set stock = stock - v_item.cantidad
     where id = v_item.producto_id and negocio_id = p_negocio_id;

    if not found then
      raise exception 'registrar_venta: product % not found for negocio %',
        v_item.producto_id, p_negocio_id;
    end if;
  end loop;

  return v_venta;
end;
$$;

grant execute on function public.registrar_venta(bigint, text, text, numeric, jsonb)
  to anon, authenticated;
