-- Production's productos.id was left without identity generation: the migration
-- history marks 20260921120000_atomic_sales_and_product_ids.sql as applied, but the
-- out-of-band schema production was built from never actually got the ALTER, so
-- inserting a new product (which omits id on purpose) hits a not-null violation.
-- Confirmed via `supabase db diff --linked`, which reported production needing
-- "ALTER COLUMN id DROP IDENTITY" to match the migrated shadow schema.
do $$
begin
  if not exists (
    select 1 from pg_attribute
    where attrelid = 'public.productos'::regclass
      and attname = 'id'
      and attidentity <> ''
  ) then
    alter table public.productos alter column id add generated by default as identity;
  end if;
end $$;

select setval(
  pg_get_serial_sequence('public.productos', 'id'),
  coalesce((select max(id) from public.productos), 0) + 1,
  false
);
